# Generated by Django 5.1.2 on 2024-10-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TheaterHall",
            new_name="TheatreHall",
        ),
        migrations.AlterModelOptions(
            name="play",
            options={"ordering": ["title"], "verbose_name_plural": "plays"},
        ),
        migrations.RenameField(
            model_name="performance",
            old_name="theater_hall",
            new_name="theatre_hall",
        ),
    ]
