# Generated by Django 5.1.2 on 2024-10-20 12:14

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_rename_theaterhall_theatrehall_alter_play_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.create_custom_path
            ),
        ),
    ]
