# Generated by Django 5.1.2 on 2024-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_play_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theatre.actor'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theatre.genre'),
        ),
    ]
